Song.create(title: "Blank Space", released: true, release_year: 2014, artist_name: "Taylor Swift", genre: "Pop")
Song.create(title: "Talisman", artist_name: "Air",release_year: 2007,released: true, genre: "Post-Rock")
Song.create(title: "Hello", artist_name: "Air",release_year: 2007,released: true, genre: "Post-Rock")
Song.create(title: "Where", artist_name: "Air",release_year: 2007,released: true, genre: "Post-Rock")
Song.create(title: "Are", artist_name: "Air",release_year: 2010,released: true, genre: "Rock")
Song.create(title: "You", artist_name: "Air",release_year: 2010,released: true, genre: "Rock")
Song.create(title: "I'm", artist_name: "Water",release_year: 2010,released: true, genre: "Rock")
Song.create(title: "Fine", artist_name: "Water",released: false, genre: "Jazz")
Song.create(title: "Alright", artist_name: "Water",released: true, genre: "New Jazz")
Song.create(title: "Gooodbye", artist_name: "Water",released: false, genre: "Pop")
Song.create(title: "Not so Blank Space", released: true, release_year: 2015, artist_name: "Taylor Swift", genre: "Pop")
Song.create(title: "Just Space", released: true, release_year: 2014, artist_name: "Taylor Swift", genre: "Rock")
Song.create(title: "Hello", released: true, release_year: 2014, artist_name: "Adele", genre: "RnB")
Song.create(title: "Chasing Pavement", released: true, release_year: 2010, artist_name: "Adele", genre: "RnB")
